// background.js

function convertToNetscapeFormat(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by YouTube Video Sender Extension',
    ''
  ];
  for (const c of cookies) {
    const domain = c.domain;
    const flag   = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path   = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'getCookies') {
    Promise.all([
      chrome.cookies.getAll({ domain: '.youtube.com' }),
      chrome.cookies.getAll({ domain: '.google.com'  }),
    ]).then(([ytCookies, gCookies]) => {
      const all       = [...ytCookies, ...gCookies];
      const cookiesTxt = convertToNetscapeFormat(all);
      sendResponse({ cookiesTxt, count: all.length });
    });
    return true; // async
  }
});
